default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['COMPOSE_PROJECT_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['COMPOSE_PROJECT_NAME'] %>_test
