version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    depends_on:
      - 'postgres'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  postgres: {}
